# Generated by Django 2.2.4 on 2019-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
